### ISSUE TITLE
Glitched selection (shader bug?)

### ISSUE THREAD

**Issue by nulldoubt** [ImMichey/Expo#2]
On Windows 11, the latest version makes the selection of objects in the world glitched out.

Here's a screenshot of what I'm talking about: 
![image](https://github.com/user-attachments/assets/18512ffa-c233-4b16-9cbd-a2532b69dd1d)

Maybe some logs would help but I'm pretty new to this game and I don't know how to obtain them!

Feel free to ask me questions, I'm looking forward to contribute to this awesome project!

**Comment by ImMichey** [comment]
Hey again @nulldoubt,

could you please provide me with your GPU model? I have observed this render bug on integrated graphics cards on Intel notebooks before.

The game _should_ automatically dump your CPU, GPU and RAM data at the start of each game launch into the latest log file located at `./clientlogs`.

**Comment by nulldoubt** [comment]
Sure thing, I couldn't find any folder called `clientlogs`, even after searching with [Everything](https://www.voidtools.com/). But [here](https://github.com/user-attachments/files/17464542/_log.txt)'s the log from the actual console. Please note that I renamed some of the file paths to keep my privacy safe 😄 

I have 2 graphics cards and the game should actually be using the integrated one (GPU1, not GPU0).
**I've tested it and the glitch actually went away after switching forcing the game to use the dedicated graphics card!**

**Comment by nulldoubt** [comment]
Actually, the issue is most likely in the `white_array` fragment shader, look at line 12. The OpenGL implementation for my Intel integrated graphics card just errors out while the one for my Nvidia graphics card compiles this shader successfully.

Look at the log file I provided previously, you can clearly see that the game first errors, then warns the user when compiling the ??`white_array` shader program, but I compared them and that exact error isn't actually logged when I run the game on my dedicated graphics card. The shader will compile successfully and the game will work fine...

I'm happy to help if you need any other infos or help debugging!

**Comment by nulldoubt** [comment]
Actually, I it might not be the `white_array` shader that's producing the bug... I modified the vertex shader and added the float input `texture_index` and the floa toutput `v_texture_index` but the bug remained...

Here's how the modified version of the `white_array.vsh` looks like, but as I said, it didn't actually change anything...: 

> #version 330
> 
> #ifdef GL_ES
> #define LOWP lowp
> precision mediump float;
> #else
> #define LOWP
> #endif
> 
> in vec4 a_position;
> in vec4 a_color;
> in vec2 a_texCoord0;
> in float texture_index;
> 
> uniform mat4 u_projTrans;
> 
> out vec4 v_color;
> out vec2 v_texCoords;
> out float v_texture_index;
> 
> void main() {
>     v_color = a_color;
>     v_color.a = v_color.a * (255.0 / 254.0);
>     v_texCoords = a_texCoord0;
>     v_texture_index = texture_index;
>     gl_Position = u_projTrans * a_position;
> }

**Comment by ImMichey** [comment]
I have commited a short fix for the `white_array.vsh` compilation warning (https://github.com/ImMichey/Expo/commit/5ca759c89da83c05fb0323ffff4e06a37b3f0391). The shader itself is not used in the current codebase, but most likely will be later on.

As of now I'm unsure why the game glitches out on Intel Integrated Graphics. Some google searches suggest that Intel's OpenGL implementation of texture arrays might be a bit wonky at times. I will continue to investigate a potential fix for the issue.

@nulldoubt, make sure to disable `DEV_MODE` in [ClientStatic.java](https://github.com/ImMichey/Expo/blob/master/core/src/main/java/dev/michey/expo/util/ClientStatic.java) if you want to have your clientlogs saved.

**Comment by nulldoubt** [comment]
Hey again @ImMichey, hope you're doing great!

I've had some time to experiment with this awesome project, it seems like this bug is basically caused by implicit behavior :/

I managed to fix it by changing this segment from the `outline.fsh` shader:
```glsl
if(c1.a > 0.0 || c2.a > 0.0 || c3.a > 0.0 || c4.a > 0.0) {
    fragColor = u_outlineColor;
    return;
}
``` 

to this: 
```glsl
if(c1.a > 0.0 || c2.a > 0.0 || c3.a > 0.0 || c4.a > 0.0) {
    fragColor = u_outlineColor;
    return;
} else {
    fragColor = vec4(0.0);
}
``` 

Adding this single `else` branch just made the glitch go away.

I'm pretty new to GitHub and Git in general, so I'm not sure how I could create a PR correctly, I'll leave you with this fix and hope you add it to this awesome project.

Have a great day!

**Comment by ImMichey** [comment]
Hey @nulldoubt, thanks for finding the error. I did commit your fix for the issue. I'm not actively working on this project as I'm working on a separate private one with a different code-base, I might port some files and features to this project in the future however (like my new developer console).

I must have overlooked this edge-case as all other shaders are handled properly. For future readers, [this](https://stackoverflow.com/a/26798000) might be helpful!

**Comment by nulldoubt** [comment]
Sure thing! I wish you great luck with your project... I also have my own projects right now but I'm really thankful to have enough time to enjoy finding some bugs in this awesome game as well ;)

If you need help or an extra dev for your other project (which I assume are at least as awesome as this one), then I'd be glad to help!
